#!/bin/sh

# PROVIDE: EcoCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# EcoCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable EcoCoin service.
# EcoCoin_config (path): Set to /usr/local/etc/EcoCoin.conf by default.
# EcoCoin_user:  The user account EcoCoin daemon runs as. It uses 'root' user by default.
# EcoCoin_group: The group account EcoCoin daemon runs as. It uses 'wheel' group by default.
# EcoCoin_datadir (str): Default to "/var/db/EcoCoin". Base data directory.

. /etc/rc.subr

name=EcoCoin
rcvar=EcoCoin_enable

: ${EcoCoin_enable:=NO}
: ${EcoCoin_config=/usr/local/etc/EcoCoin.conf}
: ${EcoCoin_datadir=/var/db/EcoCoin}
: ${EcoCoin_user="root"}
: ${EcoCoin_group="wheel"}

required_files=${EcoCoin_config}
command=/usr/local/bin/EcoCoind
EcoCoin_chdir=${EcoCoin_datadir}
pidfile="${EcoCoin_datadir}/EcoCoind.pid"
stop_cmd=EcoCoin_stop
command_args="-conf=${EcoCoin_config} -datadir=${EcoCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

EcoCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${EcoCoin_datadir}
	[ $? -eq 0 ] && chown -R ${EcoCoin_user}:${EcoCoin_group} ${EcoCoin_datadir}
}

EcoCoin_prestart()
{
	if [ ! -d "${EcoCoin_datadir}/." ]; then
		EcoCoin_create_datadir || return 1
	fi
}

EcoCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

EcoCoin_stop()
{
    EcoCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${EcoCoin_config} -datadir=${EcoCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
